i = input("enter a number")
j = input("enter other number")
a = int (i)
b = int (j)
print("sum = ",a+b)


print ("three numbers  can now added ")
k = input("enter number 3 now")
c = int(k)
print ("new sum is ", a+b+c)
print ("four numbers can now added ")
l = input("enter number 4 now")
d = int(l)
print ("new sum is ", a+b+c+d)
